/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import aluno.ArvoreAvl;
import aluno.Aluno;
import java.util.ArrayList;
import org.json.JSONObject;

/**
 *
 * @author nu4_lab201
 */
public class FrmArquivos extends javax.swing.JFrame {

    private String nomearq;
    /**
     * Creates new form FrmArquivos
     */
    public FrmArquivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArquivo = new javax.swing.JTextArea();
        carregar = new javax.swing.JButton();
        salva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arquivos");
        setName("frmArquivos"); // NOI18N

        txtArquivo.setColumns(20);
        txtArquivo.setRows(5);
        if(ArvoreAvl.raiz != null){
            ArrayList<Aluno> view = new ArrayList<Aluno>();
            ArvoreAvl viewarvore = new ArvoreAvl();
            view = viewarvore.raiz.toArrays();
            this.txtArquivo.setLineWrap(true);
            this.txtArquivo.setWrapStyleWord(true);
            System.out.println(view.size());
            if(view != null && view.get(0).getMatricula() != 0){
                for (Aluno v : view) {
                    this.txtArquivo.setText(this.txtArquivo.getText()+"matricula: "+ v.getMatricula()+", Nome: "+v.getNome()+", Curso: "+v.getCurso()+"\n");
                    System.out.println("matricula: "+ v.getMatricula()+", Nome: "+v.getNome()+", Curso: "+v.getCurso());
                }
            }
            this.txtArquivo.setEditable(false);
        }
        jScrollPane1.setViewportView(txtArquivo);

        carregar.setText("Carregar");
        carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarActionPerformed(evt);
            }
        });

        salva.setText("Salvar");
        salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salva, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carregar)
                    .addComponent(salva))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarActionPerformed
        // TODO add your handling code here:
        JFileChooser arqfc = new JFileChooser();
        arqfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = arqfc.showSaveDialog(null);

        File arq = arqfc.getSelectedFile();
        this.nomearq = arqfc.getSelectedFile().getAbsolutePath();
        FileInputStream fis = null;
        String texto = "";
        ArvoreAvl carregar = new ArvoreAvl();
        
        try {
            fis = new FileInputStream(arq);
            int linha;
            while ((linha = fis.read()) != -1) {
                texto += (char) linha;
                if((char) linha == '}'){     
                    JSONObject lerjson = new JSONObject(texto);
                    carregar.inserir(lerjson.getInt("matricula"), lerjson.getString("nome"), lerjson.getString("curso"));
                    texto = "";
                }
            }            
            
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (fis != null) {
                    fis.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        ArrayList<Aluno> view = new ArrayList<Aluno>();
        view = carregar.inorder();
         this.txtArquivo.setLineWrap(true);
            this.txtArquivo.setWrapStyleWord(true);
            System.out.println(view.size());
            if(view != null && view.get(0).getMatricula() != 0){
                for (Aluno v : view) {
                    this.txtArquivo.setText(this.txtArquivo.getText()+"matricula: "+ v.getMatricula()+", Nome: "+v.getNome()+", Curso: "+v.getCurso()+"\n");
                    System.out.println("matricula: "+ v.getMatricula()+", Nome: "+v.getNome()+", Curso: "+v.getCurso());
                }
            }
            this.txtArquivo.setEditable(false);
    }//GEN-LAST:event_carregarActionPerformed

    private void salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaActionPerformed
        try {
            // TODO add your handling code here:
            System.out.println(this.txtArquivo.getText());
            ArrayList<Aluno> listaAluno = ArvoreAvl.raiz.toArrays();
            String json = "";
            for (Aluno aluno: listaAluno) {
               JSONObject salvaJson = new JSONObject();
               salvaJson.put("matricula", aluno.getMatricula());
               salvaJson.put("nome", aluno.getNome());
               salvaJson.put("curso",aluno.getCurso());
               json += salvaJson.toString();
            }
            gravar(json);
        } catch (IOException  ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_salvaActionPerformed

    public void gravar(String texto) throws IOException{
        this.nomearq = "C:\\Users\\Matheus Paulino\\Documents\\NetBeansProjects\\ExemploArquivo\\prova\\Salva.json";
        
        File f = new File(this.nomearq);
        BufferedWriter bw = new BufferedWriter(new FileWriter(f));
        bw.write(texto);
        bw.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salva;
    private javax.swing.JTextArea txtArquivo;
    // End of variables declaration//GEN-END:variables
}
